name: Build OpenCV Windows

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true  # 如果opencv_contrib是子模块的话

      - name: Set up variables
        run: |
          echo "OPENCV_DIR=%CD%\opencv" >> $GITHUB_ENV
          echo "OPENCV_CONTRIB_DIR=%CD%\opencv_contrib" >> $GITHUB_ENV
          echo "BUILD_DIR=%CD%\build" >> $GITHUB_ENV

      - name: Create build directory
        run: mkdir build

      - name: Configure OpenCV with CMake (Visual Studio generator)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake -S "%OPENCV_DIR%" -B "%BUILD_DIR%" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_INSTALL_PREFIX="%BUILD_DIR%\install" ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DBUILD_TESTS=OFF ^
            -DBUILD_PERF_TESTS=OFF ^
            -DOPENCV_EXTRA_MODULES_PATH="%OPENCV_CONTRIB_DIR%\modules" ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

      - name: Build OpenCV
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake --build "%BUILD_DIR%" --config Release --target INSTALL

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencv-windows-release
          path: build\install
